---
- amazon.aws.ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ default_prefix }}-{{ default_stage }}-{{ default_platform }}-{{ vpc_label }}"
    register: vpc_info


- name: "Remove Virtual Private Cloud Subnet"
  ec2_vpc_subnet:
    vpc_id: "{{ vpc_info.vpcs.vpc_id }}"
    cidr: "{{ item.value.cidr }}"
    region: "{{ default_region }}"
    state: absent
  with_dict: "{{ vpc_subnets_metadata }}"
