---
- name: "Remove Virtual Private Cloud Subnet"
  ec2_vpc_subnet:
    vpc_id: "vpc-065da5218c2ed9c26"
    cidr: "{{ item.value.cidr }}"
    region: "{{ default_region }}"
    state: absent
  with_dict: "{{ vpc_subnets_metadata }}"
