---
- name: "Remove Virtual Private Cloud Subnet"
  ec2_vpc_subnet:
    vpc_id: "{{ delete_vpc_id }}"
    cidr: "{{ item.value.cidr }}"
    region: "{{ default_region }}"
    state: absent
  with_dict: "{{ vpc_subnets_metadata }}"
