---
- name: "Create Virtual Private Cloud"
  ec2_vpc_net:
    name: "{{ default_prefix }}-{{ default_account_alias }}"
    cidr_block: "{{ vpc_cidr_block }}"
    region: "{{ default_region }}"
    tags: "{{vpc_tags}}"
  register: create_vpc

- name: "Gathering Virtual Private Cloud Information"
  ansible.builtin.set_fact:
    vpc: '{{ create_vpc.vpc }}'
